name: 💡 機能リクエスト
description: 新しい機能の提案や改善要望
title: "[Feature]: "
labels: ["enhancement"]
body:
    - type: textarea
        attributes:
            label: 解決したい課題
            description: どんな不便や課題を解決したいですか？
        validations:
            required: true

    - type: textarea
        attributes:
            label: 提案する解決策
            description: どのように実装してほしいですか？
        validations:
            required: true
